import 'dotenv/config';
import express from 'express';
import { MerchantRepository } from '@vac/merchant-core';
const app = express(); app.use(express.json());
app.use((_req,res,next)=>{res.setHeader('Access-Control-Allow-Origin',process.env.WEB_ORIGIN||'http://localhost:3001');res.setHeader('Access-Control-Allow-Headers','content-type');res.setHeader('Access-Control-Allow-Methods','GET,PATCH,POST,OPTIONS');if(_req.method==='OPTIONS')return res.sendStatus(204);next();});
const repo=new MerchantRepository();
app.get('/health',(_req,res)=>res.json({ok:true})); app.get('/state',(_req,res)=>res.json({merchant:repo.merchantState(),products:repo.listProducts()})); app.get('/products',(_req,res)=>res.json(repo.listProducts()));
app.patch('/products/:id/price',(req,res)=>{try{repo.setProductPrice(req.params.id,Number(req.body.price));res.json(repo.getProduct(req.params.id))}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)})}});
app.patch('/products/:id/inventory',(req,res)=>{try{repo.setInventory(req.params.id,Number(req.body.inventory));res.json(repo.getProduct(req.params.id))}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)})}});
app.patch('/products/:id/active',(req,res)=>{try{repo.setProductActive(req.params.id,Boolean(req.body.active));res.json(repo.getProduct(req.params.id))}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)})}});
app.patch('/merchant/discount',(req,res)=>{try{repo.setDiscount(Number(req.body.discount));res.json(repo.merchantState())}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)})}});
app.patch('/merchant/delivery',(req,res)=>{try{repo.setDelivery(Number(req.body.delivery));res.json(repo.merchantState())}catch(e){res.status(400).json({error:e instanceof Error?e.message:String(e)})}});
app.post('/reset',(_req,res)=>{repo.reset();res.json({ok:true})}); const port=Number(process.env.MERCHANT_ADMIN_PORT||3002); app.listen(port,()=>console.log(`Merchant admin listening on http://localhost:${port}`));