import type Database from 'better-sqlite3';
import { randomUUID } from 'node:crypto';
import { appendAudit } from '@vac/audit';
import { DomainError, nowIso, type CartSnapshot, type Product } from '@vac/shared';
import { CURRENCY, MERCHANT_ID } from './db.js';

const mapProduct=(r:any):Product=>({id:r.id,name:r.name,category:r.category,price:r.price,inventory:r.inventory,active:!!r.active});
export const merchantState=(db:Database.Database)=>db.prepare('SELECT merchant_id merchantId,discount,delivery,tax FROM merchant_state WHERE merchant_id=?').get(MERCHANT_ID);
export const listProducts=(db:Database.Database)=>(db.prepare('SELECT id,name,category,price,inventory,active FROM products ORDER BY category,name').all() as any[]).map(mapProduct);
export function searchProducts(db:Database.Database,q0:string){const q=`%${q0.trim().toLowerCase()}%`;return (db.prepare('SELECT id,name,category,price,inventory,active FROM products WHERE active=1 AND inventory>0 AND (lower(name) LIKE ? OR lower(category) LIKE ? OR lower(id) LIKE ?) ORDER BY price ASC LIMIT 20').all(q,q,q) as any[]).map(mapProduct)}
export function getProduct(db:Database.Database,id:string){const r=db.prepare('SELECT id,name,category,price,inventory,active FROM products WHERE id=?').get(id);return r?mapProduct(r):null}
export function createCart(db:Database.Database){const id=`cart_${randomUUID()}`;db.prepare('INSERT INTO carts(id,revision,created_at) VALUES(?,0,?)').run(id,nowIso());appendAudit(db,'CART_CREATED',{cartId:id});return id}
function assertCart(db:Database.Database,id:string){if(!db.prepare('SELECT 1 FROM carts WHERE id=?').get(id))throw new Error('cart not found')}
function bump(db:Database.Database,cartId:string,data:Record<string,unknown>){db.prepare('UPDATE carts SET revision=revision+1 WHERE id=?').run(cartId);appendAudit(db,'CART_UPDATED',{cartId,...data})}
function bumpAffected(db:Database.Database,productId?:string){productId?db.prepare('UPDATE carts SET revision=revision+1 WHERE id IN(SELECT cart_id FROM cart_items WHERE product_id=?)').run(productId):db.prepare('UPDATE carts SET revision=revision+1 WHERE EXISTS(SELECT 1 FROM cart_items WHERE cart_id=carts.id)').run()}
export function addToCart(db:Database.Database,cartId:string,productId:string,quantity:number){if(!Number.isInteger(quantity)||quantity<=0)throw new Error('quantity must be a positive integer');assertCart(db,cartId);const p=getProduct(db,productId);if(!p||!p.active)throw new Error('product not found');const old=db.prepare('SELECT quantity FROM cart_items WHERE cart_id=? AND product_id=?').get(cartId,productId) as {quantity:number}|undefined;const next=(old?.quantity||0)+quantity;if(next>p.inventory)throw new Error('insufficient inventory');db.prepare('INSERT INTO cart_items(cart_id,product_id,quantity) VALUES(?,?,?) ON CONFLICT(cart_id,product_id) DO UPDATE SET quantity=excluded.quantity').run(cartId,productId,next);bump(db,cartId,{productId,quantity:next});return getCartSnapshot(db,cartId)}
export function updateQuantity(db:Database.Database,cartId:string,productId:string,quantity:number){if(!Number.isInteger(quantity)||quantity<0)throw new Error('quantity must be non-negative integer');assertCart(db,cartId);if(quantity===0)return removeFromCart(db,cartId,productId);const p=getProduct(db,productId);if(!p||!p.active||quantity>p.inventory)throw new Error('product unavailable or insufficient inventory');if(!db.prepare('UPDATE cart_items SET quantity=? WHERE cart_id=? AND product_id=?').run(quantity,cartId,productId).changes)throw new Error('product is not in cart');bump(db,cartId,{productId,quantity});return getCartSnapshot(db,cartId)}
export function removeFromCart(db:Database.Database,cartId:string,productId:string){assertCart(db,cartId);if(db.prepare('DELETE FROM cart_items WHERE cart_id=? AND product_id=?').run(cartId,productId).changes)bump(db,cartId,{productId,removed:true});return getCartSnapshot(db,cartId)}
export function getCartSnapshot(db:Database.Database,cartId:string):CartSnapshot{const cart=db.prepare('SELECT id,revision FROM carts WHERE id=?').get(cartId) as {id:string;revision:number}|undefined;if(!cart)throw new Error('cart not found');const rows=db.prepare('SELECT p.id productId,p.name,ci.quantity,p.price unitPrice,p.inventory,p.active FROM cart_items ci JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=? ORDER BY p.id').all(cartId) as any[];for(const r of rows)if(!r.active||r.quantity>r.inventory)throw new DomainError('STALE_CART','Cart contains unavailable inventory',{product_id:r.productId});const items=rows.map(r=>({productId:r.productId,name:r.name,quantity:r.quantity,unitPrice:r.unitPrice,lineTotal:r.unitPrice*r.quantity}));const subtotal=items.reduce((s,i)=>s+i.lineTotal,0);const st=db.prepare('SELECT discount,delivery,tax FROM merchant_state WHERE merchant_id=?').get(MERCHANT_ID) as any;const discount=Math.min(st.discount,subtotal),delivery=items.length?st.delivery:0,tax=st.tax,total=Math.max(0,subtotal-discount+delivery+tax);return{merchantId:MERCHANT_ID,cartId,revision:cart.revision,currency:CURRENCY,items,subtotal,discount,delivery,tax,total}}
export function setProductPrice(db:Database.Database,id:string,price:number){if(!Number.isInteger(price)||price<0)throw new Error('price must be integer paise');if(!db.prepare('UPDATE products SET price=? WHERE id=?').run(price,id).changes)throw new Error('product not found');bumpAffected(db,id);appendAudit(db,'MERCHANT_STATE_CHANGED',{kind:'PRICE',productId:id,price})}
export function setInventory(db:Database.Database,id:string,inventory:number){if(!Number.isInteger(inventory)||inventory<0)throw new Error('inventory must be non-negative integer');if(!db.prepare('UPDATE products SET inventory=? WHERE id=?').run(inventory,id).changes)throw new Error('product not found');bumpAffected(db,id);appendAudit(db,'MERCHANT_STATE_CHANGED',{kind:'INVENTORY',productId:id,inventory})}
export function setProductActive(db:Database.Database,id:string,active:boolean){if(!db.prepare('UPDATE products SET active=? WHERE id=?').run(active?1:0,id).changes)throw new Error('product not found');bumpAffected(db,id);appendAudit(db,'MERCHANT_STATE_CHANGED',{kind:'AVAILABILITY',productId:id,active})}
export function setDiscount(db:Database.Database,v:number){if(!Number.isInteger(v)||v<0)throw new Error('discount must be non-negative integer paise');db.prepare('UPDATE merchant_state SET discount=? WHERE merchant_id=?').run(v,MERCHANT_ID);bumpAffected(db);appendAudit(db,'MERCHANT_STATE_CHANGED',{kind:'DISCOUNT',discount:v})}
export function setDelivery(db:Database.Database,v:number){if(!Number.isInteger(v)||v<0)throw new Error('delivery must be non-negative integer paise');db.prepare('UPDATE merchant_state SET delivery=? WHERE merchant_id=?').run(v,MERCHANT_ID);bumpAffected(db);appendAudit(db,'MERCHANT_STATE_CHANGED',{kind:'DELIVERY',delivery:v})}
