import type Database from 'better-sqlite3';
import { appendAudit, listAudit } from '@vac/audit';
import type { AgentTaskState, Approval, ExecutionGrant, Quote } from '@vac/shared';
import { openDatabase, SEED_PRODUCTS, MERCHANT_ID } from './db.js';
import * as commerce from './commerce.js';
import * as sec from './security-state.js';
export class MerchantRepository{
  readonly db:Database.Database; constructor(path?:string){this.db=openDatabase(path)}
  reset(){this.db.transaction(()=>{this.db.exec('DELETE FROM cart_items;DELETE FROM carts;DELETE FROM quotes;DELETE FROM approvals;DELETE FROM grants;DELETE FROM executions;DELETE FROM used_nonces;DELETE FROM payment_records;DELETE FROM agent_sessions;DELETE FROM audit_events;DELETE FROM products;');const i=this.db.prepare('INSERT INTO products(id,name,category,price,inventory,active) VALUES(@id,@name,@category,@price,@inventory,@active)');SEED_PRODUCTS.forEach(p=>i.run({...p,active:p.active?1:0}));this.db.prepare('UPDATE merchant_state SET discount=3500,delivery=2500,tax=0 WHERE merchant_id=?').run(MERCHANT_ID)})();appendAudit(this.db,'MERCHANT_RESET',{})}
  merchantState=()=>commerce.merchantState(this.db); listProducts=()=>commerce.listProducts(this.db); searchProducts=(q:string)=>commerce.searchProducts(this.db,q); getProduct=(id:string)=>commerce.getProduct(this.db,id); createCart=()=>commerce.createCart(this.db); addToCart=(c:string,p:string,q:number)=>commerce.addToCart(this.db,c,p,q); updateQuantity=(c:string,p:string,q:number)=>commerce.updateQuantity(this.db,c,p,q); removeFromCart=(c:string,p:string)=>commerce.removeFromCart(this.db,c,p); getCartSnapshot=(c:string)=>commerce.getCartSnapshot(this.db,c); setProductPrice=(p:string,v:number)=>commerce.setProductPrice(this.db,p,v); setInventory=(p:string,v:number)=>commerce.setInventory(this.db,p,v); setProductActive=(p:string,v:boolean)=>commerce.setProductActive(this.db,p,v); setDiscount=(v:number)=>commerce.setDiscount(this.db,v); setDelivery=(v:number)=>commerce.setDelivery(this.db,v);
  saveQuote=(q:Quote)=>sec.saveQuote(this.db,q); getQuote=(id:string)=>sec.getQuote(this.db,id); saveApproval=(a:Approval)=>sec.saveApproval(this.db,a); getApproval=(id:string)=>sec.getApproval(this.db,id); saveGrant=(g:ExecutionGrant)=>sec.saveGrant(this.db,g); getGrant=(id:string)=>sec.getGrant(this.db,id); markGrantUsed=(id:string,at:string)=>sec.markGrantUsed(this.db,id,at); claimExecution=(id:string)=>sec.claimExecution(this.db,id); claimNonce=(n:string,g:string)=>sec.claimNonce(this.db,n,g); getExecution=(id:string)=>sec.getExecution(this.db,id); saveExecution=(id:string,s:string,o:string|null,r:unknown)=>sec.saveExecution(this.db,id,s,o,r); savePaymentRecord=(o:string,g:string,s:string,p:unknown,pid?:string,v=false)=>sec.savePaymentRecord(this.db,o,g,s,p,pid,v); getPaymentRecord=(o:string)=>sec.getPaymentRecord(this.db,o); createSession=(s:AgentTaskState,m:unknown[])=>sec.createSession(this.db,s,m); getSession=(id:string)=>sec.getSession(this.db,id); saveSession=(s:AgentTaskState,m:unknown[])=>sec.saveSession(this.db,s,m); audit=(limit=200)=>listAudit(this.db,limit);
}
