import type Database from 'better-sqlite3';
import { appendAudit } from '@vac/audit';
import { nowIso, type AgentTaskState, type Approval, type ExecutionGrant, type Quote } from '@vac/shared';
export function saveQuote(db:Database.Database,q:Quote){db.prepare('INSERT INTO quotes VALUES(@quoteId,@merchantId,@cartId,@cartRevision,@amount,@currency,@cartDigest,@issuedAt,@validUntil,@nonce,@merchantSignature)').run(q);appendAudit(db,'QUOTE_COMMITTED',{quoteId:q.quoteId,cartId:q.cartId,amount:q.amount,revision:q.cartRevision,digest:q.cartDigest})}
export function getQuote(db:Database.Database,id:string):Quote|null{const r=db.prepare('SELECT * FROM quotes WHERE quote_id=?').get(id) as any;return r?{quoteId:r.quote_id,merchantId:r.merchant_id,cartId:r.cart_id,cartRevision:r.cart_revision,amount:r.amount,currency:r.currency,cartDigest:r.cart_digest,issuedAt:r.issued_at,validUntil:r.valid_until,nonce:r.nonce,merchantSignature:r.merchant_signature}:null}
export function saveApproval(db:Database.Database,a:Approval){db.prepare('INSERT INTO approvals VALUES(@approvalId,@quoteId,@cartDigest,@amount,@currency,@expiresAt,@createdAt)').run(a);appendAudit(db,'QUOTE_APPROVED',{approvalId:a.approvalId,quoteId:a.quoteId,amount:a.amount})}
export function getApproval(db:Database.Database,id:string):Approval|null{const r=db.prepare('SELECT * FROM approvals WHERE approval_id=?').get(id) as any;return r?{approvalId:r.approval_id,quoteId:r.quote_id,cartDigest:r.cart_digest,amount:r.amount,currency:r.currency,expiresAt:r.expires_at,createdAt:r.created_at}:null}
export const saveGrant=(db:Database.Database,g:ExecutionGrant)=>db.prepare('INSERT INTO grants(grant_id,quote_id,approval_id,cart_digest,amount,currency,expires_at,nonce,used_at) VALUES(@grantId,@quoteId,@approvalId,@cartDigest,@amount,@currency,@expiresAt,@nonce,NULL)').run(g);
export function getGrant(db:Database.Database,id:string){const r=db.prepare('SELECT * FROM grants WHERE grant_id=?').get(id) as any;return r?{grantId:r.grant_id,quoteId:r.quote_id,approvalId:r.approval_id,cartDigest:r.cart_digest,amount:r.amount,currency:r.currency,expiresAt:r.expires_at,nonce:r.nonce,usedAt:r.used_at||undefined}:null}
export const markGrantUsed=(db:Database.Database,id:string,at:string)=>db.prepare('UPDATE grants SET used_at=? WHERE grant_id=? AND used_at IS NULL').run(at,id);
export function getExecution(db:Database.Database,id:string){const r=db.prepare('SELECT * FROM executions WHERE grant_id=?').get(id) as any;return r?{grantId:r.grant_id,state:r.state,orderId:r.order_id,result:r.result_json?JSON.parse(r.result_json):null,updatedAt:r.updated_at}:null}
export function saveExecution(db:Database.Database,id:string,state:string,orderId:string|null,result:unknown){db.prepare('INSERT INTO executions(grant_id,state,order_id,result_json,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(grant_id) DO UPDATE SET state=excluded.state,order_id=excluded.order_id,result_json=excluded.result_json,updated_at=excluded.updated_at').run(id,state,orderId,result==null?null:JSON.stringify(result),nowIso())}
export function claimExecution(db:Database.Database,id:string):'CLAIMED'|'EXISTING'|'RETRYABLE'{const e=getExecution(db,id);if(e?.state==='PAYMENT_FAILED'){saveExecution(db,id,'VERIFYING',null,{retry_of:e});return'RETRYABLE'}return db.prepare("INSERT OR IGNORE INTO executions(grant_id,state,order_id,result_json,updated_at) VALUES(?,'VERIFYING',NULL,NULL,?)").run(id,nowIso()).changes===1?'CLAIMED':'EXISTING'}
export function claimNonce(db:Database.Database,nonce:string,grantId:string){const e=db.prepare('SELECT grant_id FROM used_nonces WHERE nonce=?').get(nonce) as any;if(e)return e.grant_id===grantId;return db.prepare('INSERT INTO used_nonces(nonce,used_at,grant_id) VALUES(?,?,?)').run(nonce,nowIso(),grantId).changes===1}
export function savePaymentRecord(db:Database.Database,orderId:string,grantId:string,state:string,payload:unknown,paymentId?:string,verified=false){db.prepare('INSERT INTO payment_records(order_id,grant_id,payment_id,state,signature_verified,payload_json,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET payment_id=excluded.payment_id,state=excluded.state,signature_verified=excluded.signature_verified,payload_json=excluded.payload_json,updated_at=excluded.updated_at').run(orderId,grantId,paymentId||null,state,verified?1:0,JSON.stringify(payload??{}),nowIso())}
export function getPaymentRecord(db:Database.Database,id:string){const r=db.prepare('SELECT * FROM payment_records WHERE order_id=?').get(id) as any;return r?{orderId:r.order_id,grantId:r.grant_id,paymentId:r.payment_id,state:r.state,signatureVerified:!!r.signature_verified,payload:r.payload_json?JSON.parse(r.payload_json):null,updatedAt:r.updated_at}:null}
export function createSession(db:Database.Database,s:AgentTaskState,m:unknown[]){db.prepare('INSERT INTO agent_sessions(session_id,state_json,messages_json,created_at,updated_at) VALUES(?,?,?,?,?)').run(s.sessionId,JSON.stringify(s),JSON.stringify(m),s.createdAt,s.updatedAt)}
export function getSession(db:Database.Database,id:string):{state:AgentTaskState;messages:any[]}|null{const r=db.prepare('SELECT state_json,messages_json FROM agent_sessions WHERE session_id=?').get(id) as any;return r?{state:JSON.parse(r.state_json),messages:JSON.parse(r.messages_json)}:null}
export function saveSession(db:Database.Database,s:AgentTaskState,m:unknown[]){s.updatedAt=nowIso();db.prepare('INSERT INTO agent_sessions(session_id,state_json,messages_json,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET state_json=excluded.state_json,messages_json=excluded.messages_json,updated_at=excluded.updated_at').run(s.sessionId,JSON.stringify(s),JSON.stringify(m),s.createdAt,s.updatedAt)}
